#!/bin/sh

cd ~

echo "Make temp directory"
mkdir ~/temp

echo "Install Play 1.2.5"
wget http://download.playframework.org/releases/play-1.2.5.zip
unzip -q play-1.2.5.zip

echo "Use DotCloud versions of config files"
cd ~/code/
cp ~/code/conf/application.conf.dotcloud ~/code/conf/application.conf
cp ~/code/public/javascripts/config.js.template ~/code/public/javascripts/config.js

echo "Apply and play database evolutions"
../play-1.2.5/play evolutions:apply

echo "Deploy the war to temp"
../play-1.2.5/play war -o ../temp/root --zip

echo "Copy war to webapps"
mv ~/temp/root* ~/webapps/